### ISSUE TITLE
Missing setup-app.rb file

### ISSUE THREAD

**Issue by TravelTrexIT** [guardian/grid#1428] opened 2015-11-04 14:53 UTC
hi, 
we are missing the setup-app.rb script to perform step 6 command of the nginx setup. 
"sudo /setup-app.rb /nginx-mapping.yml" 
Can someone give me a hint on where to find it?

**Comment by theefer** [comment] 2015-11-04 16:06
Duplicate of https://github.com/guardian/grid/issues/1090

**Closed by theefer** 2015-11-04 16:06 UTC
