### ISSUE TITLE
./cloud-formation/scripts/post-dev-stack-creation.sh: line 18: md5hash: command not found

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [guardian/grid#2374] opened 2018-12-13 17:16 UTC
Why does it say md5hash there? As far as I know that's not a valid command on any OS?

**Comment by CaerphillyMediaLtd** [comment] 2018-12-13 17:18
I also get all other kinds of errors:

```
./cloud-formation/scripts/post-dev-stack-creation.sh media-service-DEV
Uploading config to stack media-service-DEV
./cloud-formation/scripts/post-dev-stack-creation.sh: line 18: md5hash: command not found
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 645, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 318, in service_model
    return self._get_service_model()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 207, in get_config_variable
    logical_name)
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 213, in get_config_variable
    return provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 310, in provide
    value = provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 369, in provide
    config = self._session.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 308, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (media-service) could not be found
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 645, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 318, in service_model
    return self._get_service_model()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 207, in get_config_variable
    logical_name)
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 213, in get_config_variable
    return provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 310, in provide
    value = provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 369, in provide
    config = self._session.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 308, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (media-service) could not be found
Uploading empty permissions file
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 645, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 318, in service_model
    return self._get_service_model()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 207, in get_config_variable
    logical_name)
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 213, in get_config_variable
    return provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 310, in provide
    value = provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 369, in provide
    config = self._session.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 308, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (media-service) could not be found
Creating Cropper key cropper-
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 645, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 318, in service_model
    return self._get_service_model()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 207, in get_config_variable
    logical_name)
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 213, in get_config_variable
    return provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 310, in provide
    value = provider.provide()
  File "/usr/lib/python2.7/site-packages/botocore/configprovider.py", line 369, in provide
    config = self._session.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 308, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (media-service) could not be found

```

**Comment by akash1810** [comment] 2018-12-14 08:35
Hi,

Thank you for using Grid and for reporting this issue. It looks like we have introduced a regression, apologies.

`md5hash` was an alias to `md5sum` on Linux and `md5` on OSX, see the original commit [here](https://github.com/guardian/grid/commit/dd3fce2c61c35312e6ae8a33de751ba0b823be2a#diff-bf3ab15dc8a1ee8a37466f5bf987288e). A suggested fix is [here](https://github.com/guardian/grid/pull/2376).

Regarding your stack trace, Grid expects there to be a `media-service` profile in your AWS credentials file (documented [here](https://github.com/guardian/grid/blob/master/docs/02.01-dev-setup.md#aws-credentials)). This can be added with `aws configure --profile media-service` and then following the prompts.

**Comment by akash1810** [comment] 2018-12-14 11:33
Additionally, we're actively working on making Grid easier to run outside of The Guardian. We hope to have more to share soon.

Thank you for your patience and please pass on any suggestions for improvements you may have.

**Comment by akash1810** [comment] 2019-02-12 08:30
Fixed in https://github.com/guardian/grid/pull/2376. Closing.

**Closed by akash1810** 2019-02-12 08:30 UTC
