### ISSUE TITLE
Composer galleries - images lost when no alt text is added

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/grid#1985] opened 2016-08-15 13:40 UTC
Issue raised on behalf of Tom Ross from central prod:

Problem: An image with a caption exceeding 600 characters can not be dropped and dragged into a gallery unless the caption is edited and copied into the alt text field.

Tool: Composer and The grid

Date/Time: Picture editor Jonny Weeks has found this to be the case for several months. Unfortunately we don't have a concrete date for when this began.

Browser: Chrome - latest

Steps to replicate:

Create a Composer gallery page
Add THIS image to the gallery by dragging the freeform crop into the 'Add new image' dropzone from one browser window/tab into another https://media.gutools.co.uk/images/eb07a0e9e45602d283f7b40f067c9c 73a82415de?crop=0_0_4256_2827
https://media.gutools.co.uk/images/eb07a0e9e45602d283f7b40f067c9c73a82415de?crop=0_0_4256_2827 3. Save and Close without adding alt text to the image
Click into the body field. The entire gallery is lost.
You can also produce the same result with: https://media.gutools.co.uk/images/914044e8a75b16512420b458ec0542 2e7c62cd88?crop=0_0_4352_3376

Is this any part of a pattern from what you can see: This appears to be specifically related to the alt text field in the gallery template.

This problem does NOT occur if you add images to a gallery using the embedded version of The Grid. Only when dragging from one browser window into another.

Office: Australia

Users affected: Jonny Weeks, Tom Ross

Video: https://drive.google.com/file/d/0Bw2jyL8KiufXNmZEZ0hjMGkxMWs/ view?usp=sharing

**Comment by paperboyo** [comment] 2017-07-03 00:07
Tested and not there any more (even though I can’t find a Composer PR). Safe to close, @michaelwmcnamara?

**Comment by paperboyo** [comment] 2018-07-12 07:47
Closing as cannot reproduce. Will reopen if necessary.

**Closed by paperboyo** 2018-07-12 07:47 UTC
